/* Note that we have to drop (and Create) any database called Diseases if we already have it for smooth access */
DROP DATABASE IF EXISTS DISEASES;
CREATE DATABASE DISEASES;
USE DISEASES;
DROP TABLE IF EXISTS tb;
DROP TABLE IF EXISTS population;
DROP TABLE IF EXISTS tb_population;


/* Creating our TB table */
CREATE TABLE TB (
COUNTRY varchar(255) NOT NULL,
YEARS int NOT NULL PRIMARY KEY,
sex Varchar(100),
case1 int,
case2 int,
case3 int);

/* Creating Population table */
CREATE TABLE POPULATION (
COUNTRY VARCHAR(255) NOT NULL PRIMARY KEY,
YEARS INT NOT NULL,
POPULATION INT NULL);

/* Loading data into already created tables */

LOAD DATA LOCAL INFILE 'c:/Data/tb.csv' 
INTO TABLE tb 
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

LOAD DATA LOCAL INFILE 'c:/Data/population.csv' 
INTO TABLE population 
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

/* Creating linker table called TB_Population for many-to-many table. */

CREATE TABLE TB_POPULATION (
CASE1 INT,
SEX VARCHAR(10),
YEARS int NOT NULL REFERENCES TB(YEARS),
COUNTRY VARCHAR(255) NOT NULL REFERENCES POPULATION(COUNTRY),
CONSTRAINT pk_TB_POPULATION PRIMARY KEY(YEARS, COUNTRY));


/* Loading data into TB_Populaton table */

LOAD DATA LOCAL INFILE 'c:/Data/tb_population.csv' 
INTO TABLE tb_population 
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

SELECT * FROM POPULATION;
SELECT * FROM TB;
SELECT * FROM TB_POPULATION;


SELECT T.SEX, T.CASE1+T.CASE2+T.CASE3 AS 'CASES', T.COUNTRY
FROM TB T
LEFT JOIN TB_POPULATION TP ON T.COUNTRY = TP.COUNTRY
LEFT JOIN POPULATION P ON P.YEARS = TP.YEARS
ORDER BY T.SEX, CASES, P.POPULATION asc;